#!/bin/sh

make distclean

echo Cleaning root
rm -rf aclocal.m4 \
       autom4te.cache \
       config.guess \
       config.h.in \
       config.h.in~ \
       config.sub \
       configure \
       depcomp \
       snippet \
       install-sh \
       ltmain.sh \
       missing \
       test-driver \
       compile \
       ylwrap \
       src/lex.cc \
       src/parse.h \
       src/parse.hh \
       src/parse.cc \
       src/parse.output \
       `find . -name Makefile.in`
       
