#!/bin/sh

make distclean

echo Cleaning root
rm -rf aclocal.m4 \
       autom4te.cache \
       config.guess \
       config.h.in \
       config.h.in~ \
       config.sub \
       configure \
       depcomp \
       install-sh \
       ltmain.sh \
       missing \
       ylwrap \
       `find . -name Makefile.in`
echo Cleaning m4
cd m4 && rm -rf \
       libtool.m4 \
       ltoptions.m4 \
       ltsugar.m4 \
       ltversion.m4 \
       lt~obsolete.m4
       
